site_name: RhamaaCMS Documentation
site_description: Complete documentation for RhamaaCMS - Wagtail template for rapid development
site_url: https://rhamaacms.readthedocs.io/

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.instant
    - navigation.tracking
  language: en

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Initial Setup: getting-started/initial-setup.md
    - Running Server: getting-started/running-server.md
  - User Guide:
    - Project Structure: guide/project-structure.md
    - Design System: guide/design-system.md
    - Implementation Summary: guide/implementation-summary.md
    - Theme Customization: guide/theme-customization.md
    - Component Development: guide/component-development.md
    - JavaScript Development: guide/javascript-development.md
    - Pages and Blocks: guide/pages-blocks.md
    - Content Management: guide/content-management.md
    - Template Customization: guide/template-customization.md
  - Deployment:
    - Fly.io: deployment/flyio.md
    - Divio Cloud: deployment/divio.md
    - Other Servers: deployment/other-servers.md
  - Development:
    - Contributing: development/contributing.md
    - Template Structure: development/template-structure.md
    - Testing: development/testing.md
  - FAQ: faq.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
